backend:
  name: git-gateway
  branch: main

media_folder: "public"

collections:
  - name: "quotes"
    label: "Floating Quotes"
    files:
      - name: "quotes"
        label: "Quotes"
        file: "quotes.json"
        fields:
          - name: "quotes"
            label: "Quotes"
            label_singular: "Quote"
            widget: "list"
            summary: "{{fields.quote}}"
            field:
              name: "quote"
              label: "Quote"
              widget: "string"